'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class airtime
    
    '''<summary>
    '''lbActionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbActionName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFileName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuMessages As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDept As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lsDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsDepartments As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''lbmobilenos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbmobilenos As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtMobileNos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMobileNos As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbUniqueMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUniqueMobile As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtUniqueMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUniqueMobile As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbAccountNos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAccountNos As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtAccountNos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNos As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbUniqueAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUniqueAccounts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtUniqueAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUniqueAccounts As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtMinAirtime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinAirtime As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbMaxLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbMaxLength As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtMaxAirtime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxAirtime As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCost As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCost As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gvairtime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvairtime As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnPush control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPush As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
